import type { Metadata } from "next";
import { Montserrat } from "next/font/google"; 
import "./globals.css";
import { CartProvider } from "./(routes)/cart/CartContext";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat", 
  display: "swap", 
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], 
});

export const metadata: Metadata = {
  title: "E-Commerce Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} antialiased`}>
        <CartProvider>
        {children}
        </CartProvider>
      </body>
    </html>
  );
}